services:
  # PostgreSQL Database
  postgres:
    image: postgres:17
    container_name: master_data_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-master_data}
      POSTGRES_USER: ${POSTGRES_USER:-appuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-apppassword}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - master_data_network

  # Application
  app:
    image: turahe/master-data-rest-api:latest
    container_name: master_data_api
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      APP_ENV: ${APP_ENV:-development}
      APP_PORT: ${APP_PORT:-8080}
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-master_data}
      DB_USER: ${DB_USER:-appuser}
      DB_PASSWORD: ${DB_PASSWORD:-apppassword}
      DB_DRIVER: ${DB_DRIVER:-postgres}
      DB_SSL_MODE: ${DB_SSL_MODE:-disable}
      MEILISEARCH_HOST: ${MEILISEARCH_HOST:-http://meilisearch:7700}
      MEILISEARCH_API_KEY: ${MEILISEARCH_API_KEY:-masterKey123}
    depends_on:
      - postgres
      - meilisearch
    networks:
      - master_data_network

  # Redis (optional, for caching)
  redis:
    image: redis:7-alpine
    container_name: master_data_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - master_data_network

  # Meilisearch (for search functionality)
  meilisearch:
    image: getmeili/meilisearch:v1.5
    container_name: master_data_meilisearch
    restart: unless-stopped
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: ${MEILISEARCH_API_KEY:-masterKey123}
      MEILI_ENV: ${MEILI_ENV:-development}
      MEILI_HTTP_ADDR: 0.0.0.0:7700
    volumes:
      - ./data/meilisearch:/meili_data
    networks:
      - master_data_network

networks:
  master_data_network:
    driver: bridge 