CREATE TABLE IF NOT EXISTS tm_countries (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    capital VARCHAR(255) NULL,
    citizenship VARCHAR(255) NULL,
    country_code VARCHAR(3) NOT NULL,
    currency_name VARCHAR(255) NULL,
    currency_code VARCHAR(255) NULL,
    currency_sub_unit VARCHAR(255) NULL,
    currency_symbol VARCHAR(3) NULL,
    full_name VARCHAR(255) NULL,
    iso_3166_2 VARCHAR(2) NOT NULL,
    iso_3166_3 VARCHAR(3) NOT NULL,
    name VARCHAR(255) NOT NULL,
    region_code VARCHAR(3) NULL,
    sub_region_code VARCHAR(3) NULL,
    eea BOOLEAN NOT NULL DEFAULT FALSE,
    calling_code VARCHAR(3) NOT NULL,
    flag VARCHAR(6) NULL,
    latitude VARCHAR(255) NULL,
    longitude VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_country_code (country_code),
    INDEX idx_iso_3166_2 (iso_3166_2),
    INDEX idx_iso_3166_3 (iso_3166_3),
    INDEX idx_calling_code (calling_code),
    INDEX idx_latitude (latitude),
    INDEX idx_longitude (longitude)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 