// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/api-keys": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get all API keys with pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api-keys"
                ],
                "summary": "Get all API keys",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "API keys retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new API key with the provided information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api-keys"
                ],
                "summary": "Create a new API key",
                "parameters": [
                    {
                        "description": "API key information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapters_primary_http.CreateAPIKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "API key created successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/api-keys/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get an API key by its UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api-keys"
                ],
                "summary": "Get API key by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "API key retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "API key not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update an existing API key",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api-keys"
                ],
                "summary": "Update an API key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated API key information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapters_primary_http.UpdateAPIKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "API key updated successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "API key not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Soft delete an API key",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api-keys"
                ],
                "summary": "Delete an API key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "API key deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "API key not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/api-keys/{id}/activate": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Activate a deactivated API key",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api-keys"
                ],
                "summary": "Activate an API key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "API key activated successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "API key not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/api-keys/{id}/deactivate": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Deactivate an active API key",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api-keys"
                ],
                "summary": "Deactivate an API key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "API key deactivated successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "API key not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/banks": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get all banks with pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "banks"
                ],
                "summary": "Get all banks",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Banks retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new bank with the provided information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "banks"
                ],
                "summary": "Create a new bank",
                "parameters": [
                    {
                        "description": "Bank information",
                        "name": "bank",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapters_primary_http.CreateBankRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Bank created successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/banks/code/{code}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a bank by its code",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "banks"
                ],
                "summary": "Get bank by code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bank Code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Bank retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "Bank not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/banks/search": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Search banks by name, alias, company, or code",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "banks"
                ],
                "summary": "Search banks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Banks found",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/banks/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a bank by its UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "banks"
                ],
                "summary": "Get bank by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bank ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Bank retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "Bank not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update an existing bank",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "banks"
                ],
                "summary": "Update a bank",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bank ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated bank information",
                        "name": "bank",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapters_primary_http.UpdateBankRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Bank updated successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "Bank not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete a bank by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "banks"
                ],
                "summary": "Delete a bank",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bank ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Bank deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "Bank not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/geodirectories": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get all geodirectories with pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "geodirectories"
                ],
                "summary": "Get all geodirectories",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Geodirectories retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new geodirectory with hierarchical support",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "geodirectories"
                ],
                "summary": "Create a new geodirectory",
                "parameters": [
                    {
                        "description": "Geodirectory data",
                        "name": "geodirectory",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapters_primary_http.CreateGeodirectoryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Geodirectory created successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/geodirectories/rebuild": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rebuild the nested set structure for all geodirectories",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "geodirectories"
                ],
                "summary": "Rebuild nested set structure",
                "responses": {
                    "200": {
                        "description": "Nested set rebuilt successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/geodirectories/search": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Search geodirectories by name, code, or postal code",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "geodirectories"
                ],
                "summary": "Search geodirectories",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Geodirectories found",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/geodirectories/type/{type}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get geodirectories filtered by type",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "geodirectories"
                ],
                "summary": "Get geodirectories by type",
                "parameters": [
                    {
                        "enum": [
                            "CONTINENT",
                            "SUBCONTINENT",
                            "COUNTRY",
                            "STATE",
                            "PROVINCE",
                            "REGENCY",
                            "CITY",
                            "DISTRICT",
                            "SUBDISTRICT",
                            "VILLAGE"
                        ],
                        "type": "string",
                        "description": "Geodirectory Type",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Geodirectories retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/geodirectories/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a geodirectory by its UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "geodirectories"
                ],
                "summary": "Get geodirectory by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Geodirectory ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Geodirectory retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "Geodirectory not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update an existing geodirectory",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "geodirectories"
                ],
                "summary": "Update a geodirectory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Geodirectory ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated geodirectory data",
                        "name": "geodirectory",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapters_primary_http.UpdateGeodirectoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Geodirectory updated successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "Geodirectory not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete a geodirectory and all its descendants",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "geodirectories"
                ],
                "summary": "Delete a geodirectory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Geodirectory ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Geodirectory deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "Geodirectory not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/geodirectories/{id}/ancestors": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get all ancestors of a geodirectory using nested set model",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "geodirectories"
                ],
                "summary": "Get ancestors of a geodirectory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Geodirectory ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ancestors retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "Geodirectory not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/geodirectories/{id}/children": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get direct children of a geodirectory",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "geodirectories"
                ],
                "summary": "Get children of a geodirectory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Parent Geodirectory ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter by child type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Children retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "Geodirectory not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/geodirectories/{id}/descendants": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get all descendants of a geodirectory using nested set model",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "geodirectories"
                ],
                "summary": "Get descendants of a geodirectory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Geodirectory ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Descendants retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "Geodirectory not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/geodirectories/{id}/hierarchy": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a geodirectory with its parent and children",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "geodirectories"
                ],
                "summary": "Get geodirectory with hierarchy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Geodirectory ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Geodirectory with hierarchy retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "Geodirectory not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/geodirectories/{id}/move": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Move a geodirectory and its descendants to a new parent",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "geodirectories"
                ],
                "summary": "Move a geodirectory to a new parent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Geodirectory ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Move request data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapters_primary_http.MoveGeodirectoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Geodirectory moved successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "Geodirectory not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_turahe_master-data-rest-api_pkg_response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_turahe_master-data-rest-api_pkg_response.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "internal_adapters_primary_http.CreateAPIKeyRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "expires_at": {
                    "description": "ISO 8601 format",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_adapters_primary_http.CreateBankRequest": {
            "type": "object",
            "required": [
                "alias",
                "code",
                "company",
                "name"
            ],
            "properties": {
                "alias": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "company": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_adapters_primary_http.CreateGeodirectoryRequest": {
            "type": "object",
            "required": [
                "name",
                "type"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "latitude": {
                    "type": "string"
                },
                "longitude": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "string"
                },
                "postal_code": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "internal_adapters_primary_http.MoveGeodirectoryRequest": {
            "type": "object",
            "required": [
                "new_parent_id"
            ],
            "properties": {
                "new_parent_id": {
                    "type": "string"
                }
            }
        },
        "internal_adapters_primary_http.UpdateAPIKeyRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "expires_at": {
                    "description": "ISO 8601 format",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_adapters_primary_http.UpdateBankRequest": {
            "type": "object",
            "properties": {
                "alias": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "company": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_adapters_primary_http.UpdateGeodirectoryRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "latitude": {
                    "type": "string"
                },
                "longitude": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "postal_code": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Type \"Bearer\" followed by a space and API key.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Master Data REST API",
	Description:      "A REST API for managing master data including countries, provinces, cities, districts, villages, banks, currencies, and languages.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
