name: Docker

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'Dockerfile'
      - 'docker compose.yml'
      - 'go.mod'
      - 'go.sum'
      - '**/*.go'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'Dockerfile'
      - 'docker compose.yml'
      - 'go.mod'
      - 'go.sum'
      - '**/*.go'

env:
  DOCKER_HUB_REGISTRY: docker.io
  GHCR_REGISTRY: ghcr.io
  IMAGE_NAME: turahe/master-data-rest-api

jobs:
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ env.DOCKER_HUB_REGISTRY }}/${{ env.IMAGE_NAME }}
          ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: false
        tags: ${{ env.IMAGE_NAME }}:test
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=docker,dest=/tmp/image.tar

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: /tmp/image.tar

  docker-test:
    name: Test Docker Image
    runs-on: ubuntu-latest
    needs: docker-build
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: master_data_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      meilisearch:
        image: getmeili/meilisearch:v1.5
        env:
          MEILI_MASTER_KEY: testkey123
        options: >-
          --health-cmd "curl -f http://localhost:7700/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 7700:7700

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Docker image artifact
      uses: actions/download-artifact@v4
      with:
        name: docker-image
        path: /tmp

    - name: Load Docker image
      run: |
        docker load --input /tmp/image.tar
        echo "Available images after load:"
        docker images

    - name: Test Docker image - Version
      run: |
        docker run --rm ${{ env.IMAGE_NAME }}:test version

    - name: Test Docker image - Health check
      env:
        # Test Environment Configuration
        APP_NAME: Master Data REST API Test
        APP_ENV: test
        APP_VERSION: 1.0.0
        APP_PORT: 8080
        APP_HOST: 0.0.0.0
        # Test Database Configuration
        DB_DRIVER: postgres
        DB_HOST: host.docker.internal
        DB_PORT: 5432
        DB_NAME: master_data_test
        DB_USER: testuser
        DB_PASSWORD: testpass
        DB_SSL_MODE: disable
        # Test Search Configuration
        MEILISEARCH_HOST: http://host.docker.internal:7700
        MEILISEARCH_API_KEY: testkey123
        # Test Authentication Configuration
        AUTH_REQUIRED: false
        # Test Logging Configuration
        LOG_LEVEL: debug
        LOG_FORMAT: text
        LOG_OUTPUT: stdout
      run: |
        # Start container in background
        docker run -d --name test-api \
          --add-host=host.docker.internal:host-gateway \
          -p 8080:8080 \
          -e APP_NAME="$APP_NAME" \
          -e APP_ENV="$APP_ENV" \
          -e APP_VERSION="$APP_VERSION" \
          -e APP_PORT="$APP_PORT" \
          -e APP_HOST="$APP_HOST" \
          -e DB_DRIVER="$DB_DRIVER" \
          -e DB_HOST="$DB_HOST" \
          -e DB_PORT="$DB_PORT" \
          -e DB_NAME="$DB_NAME" \
          -e DB_USER="$DB_USER" \
          -e DB_PASSWORD="$DB_PASSWORD" \
          -e DB_SSL_MODE="$DB_SSL_MODE" \
          -e MEILISEARCH_HOST="$MEILISEARCH_HOST" \
          -e MEILISEARCH_API_KEY="$MEILISEARCH_API_KEY" \
          -e AUTH_REQUIRED="$AUTH_REQUIRED" \
          -e LOG_LEVEL="$LOG_LEVEL" \
          -e LOG_FORMAT="$LOG_FORMAT" \
          -e LOG_OUTPUT="$LOG_OUTPUT" \
          ${{ env.IMAGE_NAME }}:test serve
        
        # Wait for container to start
        sleep 10
        
        # Test health endpoint
        curl -f http://localhost:8080/health || exit 1
        
        # Cleanup
        docker stop test-api
        docker rm test-api

  docker-security:
    name: Docker Security Scan
    runs-on: ubuntu-latest
    needs: docker-build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Docker image artifact
      uses: actions/download-artifact@v4
      with:
        name: docker-image
        path: /tmp

    - name: Load Docker image
      run: docker load --input /tmp/image.tar

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.24.0
      with:
        input: /tmp/image.tar
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  docker-push-dev:
    name: Push Development Image
    runs-on: ubuntu-latest
    needs: [docker-build, docker-test, docker-security]
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DOCKER_HUB_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.GHCR_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ env.DOCKER_HUB_REGISTRY }}/${{ env.IMAGE_NAME }}
          ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=develop
          type=sha,prefix=develop-

    - name: Build and push development image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  docker-compose-test:
    name: Docker Compose Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create test environment file
      run: |
        cat > .env << EOF
        # Docker Test Environment Configuration
        APP_NAME=Master Data REST API
        APP_ENV=development
        APP_VERSION=1.0.0
        APP_PORT=8080
        APP_HOST=0.0.0.0
        
        # Docker Database Configuration
        DB_DRIVER=postgres
        DB_HOST=postgres
        DB_PORT=5432
        DB_NAME=master_data
        DB_USER=postgres
        DB_PASSWORD=postgres123
        DB_SSL_MODE=disable
        
        # Docker Search Configuration
        MEILISEARCH_HOST=http://meilisearch:7700
        MEILISEARCH_API_KEY=testkey123
        
        # Docker Authentication Configuration
        AUTH_REQUIRED=false
        
        # Logging Configuration
        LOG_LEVEL=info
        LOG_FORMAT=text
        LOG_OUTPUT=stdout
        EOF

    - name: Start services with Docker Compose
      run: docker compose up -d

    - name: Wait for services to be ready
      run: |
        echo "Waiting for PostgreSQL..."
        timeout 30 bash -c 'until docker compose exec -T postgres pg_isready -U postgres; do sleep 1; done'
        
        echo "Waiting for Meilisearch..."
        timeout 30 bash -c 'until curl -f http://localhost:7700/health; do sleep 1; done'
        
        echo "Waiting for API..."
        timeout 60 bash -c 'until curl -f http://localhost:8080/health; do sleep 2; done'

    - name: Run integration tests
      run: |
        # Test database connection
        docker compose exec -T master_data_api ./master-data-api migrate status
        
        # Test API endpoints
        curl -f http://localhost:8080/health
        
        # Test with API key (if migrations create one)
        docker compose exec -T master_data_api ./master-data-api create-api-key --name "test-key" > api_key.txt || true

    - name: Show service logs on failure
      if: failure()
      run: |
        echo "=== PostgreSQL logs ==="
        docker compose logs postgres
        echo "=== Meilisearch logs ==="
        docker compose logs meilisearch
        echo "=== API logs ==="
        docker compose logs master_data_api

    - name: Cleanup
      if: always()
      run: docker compose down -v
